application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: TRUE

libraries:
- name: django
  version: "1.5"

builtins:
- django_wsgi: on

handlers:
- url: /.*
  script: wsgi.application
